### ISSUE TITLE
Need instruction on how to run the example

### ISSUE THREAD

**Issue by kandroid29** [zduny/pad-motion#2]
I need some instructions on how to run the example, just failed to figure it out

**Comment by zduny** [comment]
I've fixed a problem in example that may have caused mouse part of it to not work for some people, which is likely what caused your difficulties.
Re-download compiled example from here: [gamepad-and-mouse-server.zip](https://github.com/zduny/pad_motion/releases/download/v0.1.1/gamepad-and-mouse-server.zip) (or project main page).

Now, to answer your question directly:
To run compiled example download said zip archive, unpack it and then start contained executable - a console window should appear.
I recommend testing it with this tool: https://files.sshnuke.net/PadTest_1011.zip
Hit "Start" button first, then select first "Request data" checkbox:

![pad-test](https://user-images.githubusercontent.com/135984/93879806-b05b4e80-fcdc-11ea-8d00-71b0cb3cc686.png)


To run example from sources (assuming you have [Rust](https://www.rust-lang.org/learn/get-started) language environment installed), clone project repository (or download and unpack sources directly), navigate to project root and run following command (from PowerShell or Windows Command Line):
`
cargo run --example gamepad-and-mouse-server   
`
