### ISSUE TITLE
[Feature Request] Option to invert y-axis?

### ISSUE THREAD

**Issue by Bloodshot12** [zduny/pad-motion#7]
As the title states, I think launch parameters or a command to invert the y-axis would be very appreciated

**Comment by zduny** [comment]
You mean adding said option to this [gamepad-and-mouse-server.zip](https://github.com/zduny/pad_motion/releases/download/v0.1.1/gamepad-and-mouse-server.zip)?

`pad-motion` is a [Rust](https://www.rust-lang.org/) programming library for developing tools using Cemuhook motion protocol.
[gamepad-and-mouse-server.zip](https://github.com/zduny/pad_motion/releases/download/v0.1.1/gamepad-and-mouse-server.zip) is just an example of such tool.

But I can do it, just confirm [gamepad-and-mouse-server.zip](https://github.com/zduny/pad_motion/releases/download/v0.1.1/gamepad-and-mouse-server.zip) is what you want to have such option.

**Comment by Bloodshot12** [comment]
Yes it is gamepad-and-mouse-server, sorry for the confusion. That'd be awesome

**Comment by zduny** [comment]
I updated the example.

Download [here](https://github.com/zduny/pad-motion/releases/download/v0.1.2/gamepad-and-mouse-server.zip).

Unpack the archive and start with:
```powershell
.\gamepad-and-mouse-server.exe --invert-y
```

You can see more options available with:
```powershell
.\gamepad-and-mouse-server.exe --help
```
